server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: backend_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: auth_backend
          __path__: /var/log/backend/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            message: msg
            timestamp: time
            context: context
            userId: userId
            email: email
            action: action
            ip: ip
      - labels:
          level:
          context:
          action:
          userId:
      - timestamp:
          source: timestamp
          format: RFC3339Nano
